name: nofoma
version: "1.0"
license: "GPL-2.0-or-later"
date: 2026-05-17
description: |
    Normal forms of matrices

authors:
    - name: Meinolf Geck
      url: https://pnp.mathematik.uni-stuttgart.de/idsr/idsr1/geckmf/
    - name: Alia Bonnet
      url: mailto:alia.bonnet@rwth.aachen.de

maintainers:
    - name: Meinolf Geck
      url: https://pnp.mathematik.uni-stuttgart.de/idsr/idsr1/geckmf/
    - name: Alia Bonnet
      url: mailto:alia.bonnet@rwth.aachen.de

GAP: ">= 4.15"

needed-pkgs:
    - name: "AutPGrp"
      version: ">= 1.5"
      url: "https://gap-packages.github.io/autpgrp/"

www: https://gap-packages.github.io/nofoma
readme: README.md
packageinfo: https://gap-packages.github.io/nofoma/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/nofoma/releases/download/v1.0/nofoma-1.0.tar.gz
    - name: .tar.bz2
      url: https://github.com/gap-packages/nofoma/releases/download/v1.0/nofoma-1.0.tar.bz2

abstract: |
    This package computes the Frobenius normal form and  the Jordan-Chevalley decomposition of a (square) matrix over any field  that is available in GAP. It also computes the Jordan normal form  of matrices over finite fields.

status: dev
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    maximal vectors, Frobenius normal form, Jordan normal form, Jordan-Chevalley decomposition.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>GB26</span>]   <b class='BibAuthor'>Geck, M. and Bonnet, A.</b>,
     <i class='BibTitle'>nofoma, Normal forms of matrices,
             Version 1.0</i>
     (<span class='BibYear'>2026</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/nofoma">https://gap-packages.github.io/nofoma</a></span>.
    </p>
    

bibtex: |
    @misc{ nofoma,
      author =           {Geck, M. and Bonnet, A.},
      title =            {{nofoma}, {Normal forms of matrices}, {V}ersion 1.0},
      month =            {May},
      year =             {2026},
      note =             {GAP package},
      howpublished =     {\href          {https://gap-packages.github.io/nofoma}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{nofoma}}},
      keywords =         {maximal  vectors; Frobenius normal form; Jordan normal
                          form;              Jordan\texttt{\symbol{45}}Chevalley
                          decomposition},
      printedkey =       {GB26}
    }

