# nofoma, chapter 1
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("nofoma01.tst");

# doc/_Chapter_The_nofoma_package.xml:77-86
gap> x:=X(Rationals);;
gap> a:=x^2*(x-1)^3*(x-2)*(x-3);
x_1^7-8*x_1^6+24*x_1^5-34*x_1^4+23*x_1^3-6*x_1^2
gap> b:=x^2*(x-1)^2*(x-2)^4*(x-4);
x_1^9-14*x_1^8+81*x_1^7-252*x_1^6+456*x_1^5-480*x_1^4+272*x_1^3-64*x_1^2
gap> GcdCoprimeSplit(a,b);
[ x_1^5-4*x_1^4+5*x_1^3-2*x_1^2, x_1^4-6*x_1^3+12*x_1^2-10*x_1+3,               
  x_1^7-12*x_1^6+56*x_1^5-128*x_1^4+144*x_1^3-64*x_1^2 ]

# doc/_Chapter_The_nofoma_package.xml:100-112
gap> A:=[ [ 0, 1, 0, 1 ],
>         [ 0, 0, 0, 0 ],
>         [ 0, 1, 0, 1 ],
>         [ 1, 1, 1, 1 ] ];;
gap> x:=X(Rationals);;
gap> f:=x^6-6*x^5+12*x^4-10*x^3+3*x^2;;
gap> v:=[ 1, 1, 1, 1];;
gap> pol:=nfmCoeffsPol(f);
[ 0, 0, 3, -10, 12, -6, 1 ]
gap> PolynomialToMatVec(A,pol,v);
[ 8, -16, 8, -16 ]

# doc/_Chapter_The_nofoma_package.xml:156-176
gap> A:=[ [   5,   2,  -4,   2 ],
>         [  -1,   0,   2,  -1 ],
>         [  -1,  -1,   3,  -1 ],
>         [ -13,  -7,  14,  -6 ] ];;
gap> SpinMatVector(A,[1,0,0,0]);
[ [ [ 1, 0, 0, 0 ], [ 0, 1, -2, 1 ] ], 
  [ [ 1, 0, 0, 0 ], [ 5, 2, -4, 2 ] ], 
  [ -1, 0, 1 ],             
  [ 1, 2 ] ]                
gap> SpinMatVector(A,[0,1,0,0]);
[ [ [ 0, 1, 0, 0 ], [ 1, 0, -2, 1 ], [ 0, 0, 1, -1/2 ] ], 
  [ [ 0, 1, 0, 0 ], [ -1, 0, 2, -1 ], [ 6, 3, -4, 2 ] ], 
  [ 1, -1, -1, 1 ],         
  [ 2, 1, 3 ] ]             
gap> SpinMatVector(A,[1,1,0,0]);
[ [ [ 1, 1, 0, 0 ], [ 0, 1, 1, -1/2 ] ], 
  [ [ 1, 1, 0, 0 ], [ 4, 2, -2, 1 ] ], 
  [ 1, -2, 1 ],             
  [ 1, 2 ] ]                

# doc/_Chapter_The_nofoma_package.xml:193-207
gap> A:=[ [ 0, 1, 0, 1 ],
>         [ 0, 0, 1, 0 ],
>         [ 0, 1, 0, 1 ],
>         [ 1, 1, 1, 1 ] ];;
gap> sp:=CyclicChainMat(A);
[ [ [ 1, 0, 0, 0 ], [ 0, 1, 0, 1 ], [ 0, 0, 1, 0 ], [ 0, 0, 0, 1 ] ],
  [ [ 1, 0, 0, 0 ], [ 0, 1, 0, 1 ], [ 1, 1, 2, 1 ], [ 0, 0, 0, 1 ] ],
  [ 1, 4, 5 ] ]
gap> PrintArray(sp[2]*A*sp[2]^-1);
[ [    0,    1,    0,    0 ],  
  [    0,    0,    1,    0 ],    
  [    0,    3,    1,    0 ],    
  [  1/2,  1/2,  1/2,    0 ] ]

# doc/_Chapter_The_nofoma_package.xml:234-247
gap> A:=[ [  2,  2,  0,  1,  0,  2,  1 ],
>         [  0,  4,  0,  0,  0,  1,  0 ],
>         [  0,  1,  1,  0,  0,  1,  1 ],
>         [  0, -1,  0,  1,  0, -1,  0 ],
>         [  0, -7,  0,  0,  1, -5,  0 ],
>         [  0, -2,  0,  0,  0,  1,  0 ],
>         [  0, -1,  0,  0,  0, -1,  1 ] ];;
gap> MaximalVectorMat(A);
[ [ 1, -2, 1, 1, 0, 0, 1 ], x_1^4-7*x_1^3+17*x_1^2-17*x_1+6 ]
gap> v:=last[1];;               
gap> SpinMatVector(A,v)[3];         
[ 6, -17, 17, -7, 1 ]                    

# doc/_Chapter_The_nofoma_package.xml:298-309
gap> v:=[ 1, 1, 1, 1 ];;
gap> A:=[ [ 0, 1, 0, 1 ],
>         [ 0, 0, 1, 0 ],
>         [ 0, 1, 0, 1 ],
>         [ 1, 1, 1, 1 ] ];;
gap> PrintArray(RatFormStep1(A,v)[1]);
[ [  0,  1,  0,  0 ],    
  [  0,  0,  1,  0 ],    
  [  0,  3,  1,  0 ],    
  [  1,  0,  0,  0 ] ] 

# doc/_Chapter_The_nofoma_package.xml:351-377
gap> A:=[ [  2,  2,  0,  1,  0,  2,  1 ],
>         [  0,  4,  0,  0,  0,  1,  0 ],
>         [  0,  1,  1,  0,  0,  1,  1 ],
>         [  0, -1,  0,  1,  0, -1,  0 ],
>         [  0, -7,  0,  0,  1, -5,  0 ],
>         [  0, -2,  0,  0,  0,  1,  0 ],
>         [  0, -1,  0,  0,  0, -1,  1 ] ];;
gap> f:=FrobeniusNormalForm(A);
[ [ x_1^4-7*x_1^3+17*x_1^2-17*x_1+6, x_1^2-3*x_1+2, x_1-1 ], 
  [ [    1,   -2,    1,    1,    0,    0,    1 ],
    [    2,   -7,    1,    2,    0,   -1,    3 ],
    [    4,  -26,    1,    4,    0,   -8,    6 ],
    [    8,  -89,    1,    8,    0,  -35,   11 ],
    [ -1/2,   -2,    0,  1/2,    0,   -2, -3/2 ],
    [   -1,   -4,    0,    0,    0,   -4,   -2 ],
    [    0,  9/4,    0,   -3,    1,  5/4,  1/4 ] ],
  [ 1, 5, 7 ]  ]                 
gap> PrintArray(f[2]*A*f[2]^-1);
[ [   0,   1,   0,   0,   0,   0,   0 ], 
  [   0,   0,   1,   0,   0,   0,   0 ],
  [   0,   0,   0,   1,   0,   0,   0 ],
  [  -6,  17, -17,   7,   0,   0,   0 ],
  [   0,   0,   0,   0,   0,   1,   0 ],
  [   0,   0,   0,   0,  -2,   3,   0 ],
  [   0,   0,   0,   0,   0,   0,   1 ] ]

# doc/_Chapter_The_nofoma_package.xml:392-402
gap> A := [ [ 2,  2, 0, 1, 0,  2, 1 ],
>           [ 0,  4, 0, 0, 0,  1, 0 ],
>           [ 0,  1, 1, 0, 0,  1, 1 ],
>           [ 0, -1, 0, 1, 0, -1, 0 ],
>           [ 0, -7, 0, 0, 1, -5, 0 ],
>           [ 0, -2, 0, 0, 0,  1, 0 ],
>           [ 0, -1, 0, 0, 0, -1, 1 ] ];;
gap> InvariantFactorsMat(A);
  [ x_1^4-7*x_1^3+17*x_1^2-17*x_1+6, x_1^2-3*x_1+2, x_1-1 ]

# doc/_Chapter_The_nofoma_package.xml:423-446
gap> A:=[ [  6, -2,  6,  1,  1 ],
>         [  1, -1,  2,  1, -2 ],
>         [ -2,  0, -1,  0, -1 ],
>         [ -1,  0, -2,  2, -1 ],
>         [ -4,  4, -6, -2,  3 ] ];;
gap> jc:=JordanChevalleyDecMat(A,MinimalPolynomial(A));
[ [ [  4,  0,  4, -1,  1 ], 
    [  1,  0,  1,  1, -1 ], 
    [ -1, -1,  0,  1, -1 ], 
    [  0,  0, -2,  3,  0 ], 
    [ -3,  2, -4, -1,  2 ] ], 
  [ [  2, -2,  2,  2,  0 ], 
    [  0, -1,  1,  0, -1 ], 
    [ -1,  1, -1, -1,  0 ], 
    [ -1,  0,  0, -1, -1 ], 
    [ -1,  2, -2, -1,  1 ] ] ]
gap> MinimalPolynomial(jc[1]);
x_1^3-5*x_1^2+9*x_1-5
gap> Factors(last);
[ x_1-1, x_1^2-4*x_1+5 ]  
gap> MinimalPolynomial(jc[2]);
x_1^2                     

# doc/_Chapter_The_nofoma_package.xml:474-490
gap> A := [ [ Z(5)^2, 0*Z(5), Z(5)^2, Z(5)^3, Z(5) ], 
>    [ 0*Z(5), 0*Z(5), Z(5)^3, Z(5), Z(5)^0 ],  
>    [ Z(5), Z(5)^0, 0*Z(5), Z(5)^0, 0*Z(5) ],
>    [ Z(5)^0, Z(5)^0, Z(5)^0, 0*Z(5), Z(5)^3 ],
>    [ Z(5), 0*Z(5), Z(5)^3, 0*Z(5), Z(5)^3 ] ];;
gap> B := PrimaryDecomp(A);;
gap> Display(B[2]);
[ 1, 4 ]
gap> Factors(MinimalPolynomial(A));
[ x_1-Z(5)^0, x_1^4-x_1^3+Z(5)^3*x_1+Z(5)^3 ]
gap> PrimA := A^Inverse(B[1]);;
gap> MinimalPolynomial(PrimA{[1..1]}{[1..1]});
x_1-Z(5)^0
gap> MinimalPolynomial(PrimA{[2..5]}{[2..5]});
x_1^4-x_1^3+Z(5)^3*x_1+Z(5)^3

# doc/_Chapter_The_nofoma_package.xml:507-522
gap> A := [ [ 0*Z(5), 0*Z(5), Z(5)^3, Z(5)^3, Z(5)^3, Z(5)^0 ], 
>    [ 0*Z(5), Z(5)^2, Z(5)^2, Z(5)^0, Z(5)^3, Z(5)^3 ], 
>    [ Z(5)^0, Z(5)^0, Z(5)^3, Z(5)^2, Z(5)^0, Z(5) ], 
>    [ 0*Z(5), Z(5)^3, Z(5), Z(5), 0*Z(5), Z(5)^2 ], 
>    [ Z(5)^2, Z(5)^0, Z(5)^0, 0*Z(5), Z(5), Z(5) ], 
>    [ 0*Z(5), Z(5)^0, Z(5)^2, Z(5), Z(5), Z(5) ] ];;
gap> B := JordanNormalform(A);;
gap> Display(A^Inverse(B));
3 . . . . .
. 1 . . . .
. . . 1 . .
. . 2 . . .
. . . . . 1
. . . . 3 4

#
gap> STOP_TEST("nofoma01.tst", 1);
