# nofoma, chapter 2
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("nofoma01.tst");

# doc/_Chapter_Normal_forms_of_matrices.xml:44-70
gap> A:=[ [  2,  2,  0,  1,  0,  2,  1 ],
>         [  0,  4,  0,  0,  0,  1,  0 ],
>         [  0,  1,  1,  0,  0,  1,  1 ],
>         [  0, -1,  0,  1,  0, -1,  0 ],
>         [  0, -7,  0,  0,  1, -5,  0 ],
>         [  0, -2,  0,  0,  0,  1,  0 ],
>         [  0, -1,  0,  0,  0, -1,  1 ] ];;
gap> f:=FrobeniusNormalForm(A);
[ [ x_1^4-7*x_1^3+17*x_1^2-17*x_1+6, x_1^2-3*x_1+2, x_1-1 ], 
  [ [    1,   -2,    1,    1,    0,    0,    1 ],
    [    2,   -7,    1,    2,    0,   -1,    3 ],
    [    4,  -26,    1,    4,    0,   -8,    6 ],
    [    8,  -89,    1,    8,    0,  -35,   11 ],
    [ -1/2,   -2,    0,  1/2,    0,   -2, -3/2 ],
    [   -1,   -4,    0,    0,    0,   -4,   -2 ],
    [    0,  9/4,    0,   -3,    1,  5/4,  1/4 ] ],
  [ 1, 5, 7 ]  ]                 
gap> PrintArray(f[2]*A*f[2]^-1);
[ [   0,   1,   0,   0,   0,   0,   0 ], 
  [   0,   0,   1,   0,   0,   0,   0 ],
  [   0,   0,   0,   1,   0,   0,   0 ],
  [  -6,  17, -17,   7,   0,   0,   0 ],
  [   0,   0,   0,   0,   0,   1,   0 ],
  [   0,   0,   0,   0,  -2,   3,   0 ],
  [   0,   0,   0,   0,   0,   0,   1 ] ]

# doc/_Chapter_Normal_forms_of_matrices.xml:86-104
gap> A:=[ [  2,  2,  0,  1,  0,  2,  1 ],
>         [  0,  4,  0,  0,  0,  1,  0 ],
>         [  0,  1,  1,  0,  0,  1,  1 ],
>         [  0, -1,  0,  1,  0, -1,  0 ],
>         [  0, -7,  0,  0,  1, -5,  0 ],
>         [  0, -2,  0,  0,  0,  1,  0 ],
>         [  0, -1,  0,  0,  0, -1,  1 ] ];;
gap> facs := InvariantFactorsMat(A);
[ x_1^4-7*x_1^3+17*x_1^2-17*x_1+6, x_1^2-3*x_1+2, x_1-1 ]
gap> Rat1 := CreateNormalForm(facs);
[ [ 0, 1, 0, 0, 0, 0, 0 ], [ 0, 0, 1, 0, 0, 0, 0 ], 
[ 0, 0, 0, 1, 0, 0, 0 ], [ -6, 17, -17, 7, 0, 0, 0 ], 
[ 0, 0, 0, 0, 0, 1, 0 ], [ 0, 0, 0, 0, -2, 3, 0 ], 
[ 0, 0, 0, 0, 0, 0, 1 ] ]
gap> Rat2 := A^Inverse(FrobeniusNormalForm(A)[2]);;
gap> Rat1 = Rat2;
true

# doc/_Chapter_Normal_forms_of_matrices.xml:119-129
gap> A := [ [ 2,  2, 0, 1, 0,  2, 1 ],
>           [ 0,  4, 0, 0, 0,  1, 0 ],
>           [ 0,  1, 1, 0, 0,  1, 1 ],
>           [ 0, -1, 0, 1, 0, -1, 0 ],
>           [ 0, -7, 0, 0, 1, -5, 0 ],
>           [ 0, -2, 0, 0, 0,  1, 0 ],
>           [ 0, -1, 0, 0, 0, -1, 1 ] ];;
gap> InvariantFactorsMat(A);
  [ x_1^4-7*x_1^3+17*x_1^2-17*x_1+6, x_1^2-3*x_1+2, x_1-1 ]

# doc/_Chapter_Normal_forms_of_matrices.xml:157-172
gap> A := [ [ 0*Z(5), 0*Z(5), Z(5)^3, Z(5)^3, Z(5)^3, Z(5)^0 ], 
>    [ 0*Z(5), Z(5)^2, Z(5)^2, Z(5)^0, Z(5)^3, Z(5)^3 ], 
>    [ Z(5)^0, Z(5)^0, Z(5)^3, Z(5)^2, Z(5)^0, Z(5) ], 
>    [ 0*Z(5), Z(5)^3, Z(5), Z(5), 0*Z(5), Z(5)^2 ], 
>    [ Z(5)^2, Z(5)^0, Z(5)^0, 0*Z(5), Z(5), Z(5) ], 
>    [ 0*Z(5), Z(5)^0, Z(5)^2, Z(5), Z(5), Z(5) ] ];;
gap> B := JordanNormalform(A);;
gap> Display(A^Inverse(B[1]));
3 . . . . .
. 1 . . . .
. . . 1 . .
. . 2 . . .
. . . . . 1
. . . . 3 4

#
gap> STOP_TEST("nofoma01.tst", 1);
